apiVersion: v1
kind: Namespace
metadata:
  name: dev 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student
  template:
    metadata:
      labels:
        app: student
    spec:
      containers:
      - name: student-container
        image: ravi2krishna/login-2601:student
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: student-service
  namespace: dev
spec:
  ports:
    - name: http
      port: 80
      nodePort: 31000
  selector:
    app: student
  type: NodePort