apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: login-container
        image: ravi2krishna/login-2601
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: login-service
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: login
  type: LoadBalancer