# Means Comment - Ignored by k8s 

# Yaml files can have .yaml or .yml as extensions 

# https://developer.ibm.com/tutorials/yaml-basics-and-usage-in-kubernetes/

# Simple Key Values 
key: value 
name: ravi
course: devops

# Dictionaries: Set of key values
trainer:
  name: ravi
  course: devops
  location: hyderabad 

# Lists: Multiple values 
courses:
- devops
- aws
- azure 
- python 

# real world k8s files 
apiVersion: v1 # key value
kind: Pod  # key value
metadata: # dictionary 
  name: nginx
spec: # dictionary 
  containers: # list 
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80

